export const POKEMON_DESCRIPTIONS: Record<string, string> = {
    1: "A small, quadruped Pokémon with a green plant bulb on its back. It absorbs sunlight to fuel its growth, and the bulb blooms as it evolves.",
    2: "Its body grows sturdier, and the plant on its back begins to sprout leaves and a bud. It relies on sunlight to power its moves.",
    3: "The plant on its back is fully bloomed, radiating energy. It can harness sunlight for powerful Grass-type attacks.",
    4: "A fiery lizard Pokémon with a flame burning at the tip of its tail, signaling its life force. It is energetic and fiercely loyal.",
    5: "Its fire burns hotter as it grows. It trains constantly, using its flames to intimidate foes and defend territory.",
    6: "A powerful flying lizard with wings and a blazing tail. Its fire can melt boulders and it soars majestically in battle.",
    7: "A tiny turtle Pokémon that squirts water from its mouth to protect itself. Its shell provides sturdy defense.",
    8: "Its tail and shell become stronger as it grows. It can launch jets of water with great accuracy and force.",
    9: "A massive water turtle Pokémon with heavy armor and cannons that shoot pressurized water. It is formidable both on land and sea.",
    10: "A small green caterpillar Pokémon that crawls quietly in foliage. It spins silk to protect itself and prepare for evolution.",
    11: "Its body hardens as it becomes encased in a protective cocoon. It remains mostly immobile while it prepares for transformation.",
    12: "A graceful butterfly Pokémon with large, colorful wings. It flutters lightly and can unleash powerful powder attacks.",
    13: "A tiny, sharp-stingered bug that is quick to defend itself. It uses its poison to deter predators.",
    14: "A cocoon stage Pokémon that is immobile but building strength inside. Its outer shell is very tough.",
    15: "A fast, aggressive bug Pokémon with twin stingers. It attacks in swarms and is highly territorial.",
    16: "A small, common bird Pokémon. It is quick, agile, and flutters between fields and forests with ease.",
    17: "A keen-eyed bird that patrols its territory, using its speed to chase intruders and search for food.",
    18: "A large, majestic bird Pokémon that can fly long distances. Its sharp eyes spot prey from high above.",
    19: "A small, nimble rodent Pokémon. It is quick to flee from danger but can defend itself with sharp teeth.",
    20: "A normal rodent Pokémon with strong incisors. It gnaws through obstacles and is persistent in battle.",
    21: "A feisty, tiny bird with a loud cry. It is very protective of its nest and territory.",
    22: "A long-beaked bird that flies at high speed. Its precision attacks make it a skilled hunter.",
    23: "A sly, coiled snake Pokémon that hunts stealthily. It can deliver venom with a swift strike.",
    24: "A large, intimidating serpent Pokémon with a patterned hood. It uses constriction and venom to subdue foes.",
    25: "An electric mouse Pokémon that stores electricity in its cheeks. It releases sparks when excited or threatened.",
    26: "A larger electric rodent capable of powerful bolts. It is fast and agile, using electricity both offensively and defensively.",
    27: "A small ground-dwelling Pokémon that burrows into sand for protection. Its thick hide shields it from attacks.",
    28: "A spiny ground Pokémon that curls into a ball and rolls into opponents. Its claws are sharp and durable.",
    29: "A small poison Pokémon with gentle temperament. It moves cautiously and relies on venom for protection.",
    30: "A larger poison Pokémon that is more robust and defensive. Its horns are capable of inflicting significant damage.",
    31: "A mighty poison/ground Pokémon with a tough armored hide. It has strong horns and uses brute force in battle.",
    32: "A small, spiky male poison Pokémon. It is energetic and often tests its strength through sparring.",
    33: "An aggressive poison Pokémon with sharp horns. It often engages in battle to assert dominance.",
    34: "A powerful poison/ground Pokémon with a massive horn. It can charge into enemies with devastating impact.",
    35: "A small fairy-like Pokémon known for its playful and mischievous nature. It often appears at night.",
    36: "A larger, gentle fairy Pokémon that can use magic to calm or heal. Its presence is soothing to others.",
    37: "A small fire fox Pokémon with six tails. Its flame is warm and flickers in response to emotion.",
    38: "A mystical fox Pokémon with nine long tails. Each tail is imbued with ancient energy and grace.",
    39: "A balloon-like Pokémon that sings sweetly. Its lullabies can soothe or put adversaries to sleep.",
    40: "A larger singing Pokémon that uses its voice to influence its environment. Its songs are melodic and powerful.",
    41: "A small dinosaur Pokémon with a rocky shell. It is sturdy and gains strength as it grows.",
    42: "A dinosaur-like Pokémon with protective spikes and growing horns. It uses them to fend off attackers.",
    43: "A massive dinosaur Pokémon with hard armor and a menacing horn. It commands respect in battle.",
    44: "A normal flying Pokémon that darts through the skies. It is alert and quick to react.",
    45: "A skilled bird Pokémon with keen eyes and sharp talons. It hunts small prey efficiently.",
    46: "A majestic bird Pokémon capable of long flights. Its speed and agility make it a formidable opponent.",
    47: "A stealthy snake Pokémon that hides in grass. It strikes unexpectedly with venom.",
    48: "A large, poisonous snake Pokémon with distinctive patterns. It intimidates foes with its presence.",
    49: "A small bug Pokémon that is quick and agile. It uses its stinger to protect itself.",
    50: "A bug Pokémon encased in a protective shell. It waits patiently for the right moment to strike.",
    51: "A butterfly Pokémon with vivid wings. It flits gracefully and attacks with precision.",
    52: "A tiny rodent Pokémon that is extremely alert. It uses its speed to evade danger.",
    53: "A nimble rodent Pokémon with sharp teeth. It is a tenacious forager and fighter.",
    54: "A bird Pokémon that patrols wide areas. Its sharp gaze and rapid flight make it a skilled scout.",
    55: "A larger bird Pokémon that dominates the skies. It attacks with precision and agility.",
    56: "A slithering snake Pokémon that strikes quickly. Its venom is potent against prey.",
    57: "A formidable snake Pokémon with venomous attacks and a commanding presence.",
    58: "An electric rodent Pokémon that stores electricity in its cheeks. Sparks fly when it is startled or excited.",
    59: "A more powerful electric rodent that can unleash bolts strong enough to affect large foes.",
    60: "A small ground Pokémon that digs through sand to create safe tunnels. Its armor is robust.",
    61: "A larger ground Pokémon with claws for burrowing and defending its territory.",
    62: "A gentle female poison Pokémon with a sturdy body. It protects itself and others with venomous spines.",
    63: "A robust female poison Pokémon that uses its strength to fend off threats.",
    64: "A strong poison/ground Pokémon with a massive horn and tough hide. It dominates in physical battles.",
    65: "A tiny, cute fairy Pokémon that is playful and curious. It can emit soothing light.",
    66: "A larger, magical fairy Pokémon that uses gentle powers to influence its surroundings.",
    67: "A small fire fox Pokémon with a bushy tail. Its flame burns according to its mood.",
    68: "A mystical nine-tailed fox Pokémon. Its tails are imbued with magical energy.",
    69: "A balloon-like Pokémon that sings to induce sleep in others. It floats gently as it moves.",
    70: "A larger, melodic Pokémon whose song can affect the emotions of those nearby.",
    71: "A tiny dinosaur Pokémon with rocky armor. Its sturdy body protects it from predators.",
    72: "A dinosaur Pokémon with defensive spikes. It is both strong and resilient.",
    73: "A massive dinosaur Pokémon with a tough hide and powerful attacks. Its presence commands respect.",
    74: "A flying Pokémon that darts through forests and fields. It is alert and agile.",
    75: "A bird Pokémon with sharp vision and claws. It is a capable hunter.",
    76: "A majestic flying Pokémon that travels long distances. It is swift and vigilant.",
    77: "A sneaky snake Pokémon that uses camouflage and venom to catch prey.",
    78: "A poisonous snake Pokémon that intimidates foes with its patterned hood.",
    79: "A bug Pokémon that uses its wings to flutter gracefully and evade attacks.",
    80: "A small water Pokémon with a hard shell. It squirts water to defend itself.",
    81: "A larger water turtle Pokémon with powerful cannons. It is a strategic fighter.",
    82: "A nimble bird Pokémon that is always alert. It can react quickly to threats.",
    83: "A skilled bird Pokémon with precise flight and keen eyesight. It is a natural hunter.",
    84: "A majestic flying Pokémon with impressive speed. It dominates its territory.",
    85: "A stealthy snake Pokémon that ambushes unsuspecting prey.",
    86: "A large snake Pokémon with potent venom and intimidating size.",
    87: "A small rodent Pokémon that relies on speed to survive and forage.",
    88: "A robust rodent Pokémon with sharp teeth and strong defenses.",
    89: "A bird Pokémon that flutters rapidly and is protective of its nest.",
    90: "A swift flying bird Pokémon that can strike foes with precision.",
    91: "A soaring bird Pokémon with sharp vision and fast wings.",
    92: "A tiny poison snake Pokémon that moves silently through grass.",
    93: "A large snake Pokémon with a distinctive pattern and venomous bite.",
    94: "A timid ghost/poison Pokémon that lurks in abandoned places.",
    95: "A large ghost/poison Pokémon that spreads fear and uses its spectral powers.",
    96: "A small ghost Pokémon that drifts silently in the night.",
    97: "A ghostly Pokémon with the power to manipulate the environment around it.",
    98: "A small, pale water Pokémon that has a mischievous personality.",
    99: "A larger, eerie water Pokémon with strong abilities in lakes and rivers.",
    100: "A legendary water Pokémon said to appear before storms. Its presence brings awe.",
    101: "A floating serpent Pokémon that can strike with electric shocks.",
    102: "A sea-dwelling Pokémon that uses electric currents to hunt.",
    103: "A giant water Pokémon that controls waves and can crush ships.",
    104: "A small grass Pokémon with a thick shell for protection.",
    105: "A shell-protected grass Pokémon that moves slowly but is durable.",
    106: "A towering grass Pokémon with foliage that spreads widely and can attack.",
    107: "A small, cheerful bug Pokémon with strong mandibles.",
    108: "A bug Pokémon that burrows and strikes with its pincers.",
    109: "A giant bug Pokémon that can shred trees and overpower opponents.",
    110: "A tiny rodent Pokémon that scurries in packs. Its tail sparks electricity.",
    111: "A nimble electric rodent Pokémon capable of powerful electric attacks.",
    112: "A massive electric rodent Pokémon with speed and agility unmatched in forests.",
    113: "A small water Pokémon that darts in and out of rivers.",
    114: "A fish Pokémon that uses its tail to leap and strike.",
    115: "A large fish Pokémon that hunts in schools and is highly agile.",
    116: "A playful ghost Pokémon that hides in shadows and scares those nearby.",
    117: "A ghost Pokémon that manipulates objects and enjoys pranks on people.",
    118: "A massive dragon Pokémon that can breathe fire and fly swiftly.",
    119: "A legendary dragon Pokémon with immense power and fiery attacks.",
    120: "A psychic Pokémon that levitates and manipulates objects with its mind.",
    121: "A mystical psychic Pokémon capable of foresight and mental manipulation.",
    122: "A rare, mysterious Pokémon said to be the ancestor of all other Pokémon.",
    123: "A fire-breathing dragon Pokémon with powerful wings. It guards its territory fiercely and can scorch the sky with flames.",
    124: "A serpent-like dragon Pokémon that glides through the air, striking with speed and precision.",
    125: "A mighty dragon Pokémon covered in tough scales, known for its fierce and relentless attacks.",
    126: "A dragon Pokémon that can unleash energy blasts from its mouth. Its roar can be heard for miles.",
    127: "A legendary dragon Pokémon that commands the skies with both strength and grace.",
    128: "A fire-type dragon with blazing wings. Its fierce temper matches its powerful flames.",
    129: "A water-dwelling dragon Pokémon that moves gracefully in the seas, creating massive waves.",
    130: "A legendary water dragon that controls tides and currents, rarely seen by humans.",
    131: "An elusive bird Pokémon that radiates electric energy, quick to fly and swift to strike.",
    132: "A mythical electric bird that uses powerful lightning to stun opponents in battle.",
    133: "A playful ice Pokémon that glides over frozen lakes. Its icy touch can freeze objects instantly.",
    134: "A frosty Pokémon that thrives in snowy regions. Its icy powers are both defensive and offensive.",
    135: "A small psychic Pokémon that floats in the air, using its powers to manipulate small objects.",
    136: "A psychic Pokémon with strong telekinetic abilities. It often uses its mind to assist allies.",
    137: "A ghostly Pokémon that wanders graveyards at night, invisible to most humans.",
    138: "A spooky ghost Pokémon that enjoys tricking unsuspecting people with illusions and whispers.",
    139: "A small rock Pokémon that dwells in mountains and caves. Its body is dense and sturdy.",
    140: "A rock Pokémon with a rugged shell, capable of withstanding heavy impacts.",
    141: "A massive rock Pokémon with incredible defensive strength, rarely leaving its mountainous home.",
    142: "A plant Pokémon with vibrant petals. It absorbs sunlight to enhance its energy for battle.",
    143: "A plant Pokémon whose flower releases fragrances that calm nearby creatures.",
    144: "A legendary plant Pokémon said to control the seasons with its mystical powers.",
    145: "A fiery bird Pokémon that emerges from flames, feared for its scorching attacks.",
    146: "A legendary fire bird capable of flying at incredible speeds, leaving trails of fire behind.",
    147: "An aquatic bird Pokémon that dives gracefully into water. Its movements are elegant and precise.",
    148: "A legendary water bird that rules oceans and can create storms with its wings.",
    149: "A massive ground Pokémon with immense strength. Its movements can shake the earth itself.",
    150: "A legendary ground Pokémon capable of causing earthquakes. It is revered for its raw power.",
    151: "A mythical psychic Pokémon said to hold the genetic codes of all Pokémon within its body, extremely elusive."
  };
  